add WormLikeChainOffsetPotential
Mjolnir-MD/Mjolnir pull request #273
Opened 2021-01-12 16:06 UTC by yutakasi634

WormLikeChain potential with the offset of the distance between two particles.
This PR contains
- Implementation
- test
- document (en, ja)
.
The offset version is separated from WormLikeChain potential to avoid calculation overhead in the original.

2021-01-13 17:49 UTC, ToruNiina requested changes
Basically it looks good to me.

But I have several very nitpicky comments (with suggestions). Could you resolve them?

2021-01-13 17:49 UTC, ToruNiina commented on book/content.en/docs/reference/forcefields/local/bondlength/WormLikeChainOffsetPotential.md
> +weight = 600000
This value regulates the order in the menu bar. I think the best location of this potential is the next to the WormLikeChain potential, so `700000` is better.
```suggestion
weight = 700000
```

2021-01-13 17:49 UTC, ToruNiina commented on mjolnir/forcefield/local/WormLikeChainOffsetPotential.cpp
> +    template class WormLikeChainOffsetPotential<float>;
Although it is a nitpicking, normally, we don't have any space here.
```suggestion
template class WormLikeChainOffsetPotential<double>;
template class WormLikeChainOffsetPotential<float>;
```

2021-01-14 06:03 UTC, yutakasi634 commented
Thank you for your good suggestion.
I resolved those points!

2021-01-14 07:46 UTC, ToruNiina requested changes
Oh, wait, don't you have a test?

2021-01-14 10:58 UTC, yutakasi634 commented
I'm so sorry...
I added the test and fixed some parts.
Please check this.

2021-01-14 14:53 UTC, ToruNiina approved these changes
LGTM.

2021-01-14 15:20 UTC, merged