feat: enable reduce_margin to return bool
Mjolnir-MD/Mjolnir pull request #279
Opened 2021-01-29 07:58 UTC by yutakasi634

The global interaction which I'm implementing now (https://github.com/Mjolnir-MD/Mjolnir/pull/236) needs the information that the neighbor list is updated or not in the current simulation step.
The interaction, which is based on GlobalInteractionBase, calls reduce_margin of SpatialPartiion, so, in this PR, I enable this reduce_margin method can notify that information via returned bool value.

2021-01-29 09:09 UTC, ToruNiina commented
Lookes good! I think the same applies to the `scale_margin`, because it does almost the same thing. Do you have time to do that? Or I can send a PR to your (forked) repo.

2021-01-29 09:12 UTC, yutakasi634 commented
OK, I'll do that, so wait for a while.

2021-01-29 09:59 UTC, yutakasi634 commented
Thank you for your good suggestion. I've done!

2021-01-29 10:15 UTC, ToruNiina requested changes
It is almost okay, but I found a function that is overlooked.

2021-01-29 10:15 UTC, ToruNiina commented on mjolnir/core/SpatialPartitionBase.hpp
>      void scale_margin(const real_type scale, const system_type& sys,
It seems that you forgot to apply the change here.

2021-01-29 10:16 UTC, ToruNiina commented on mjolnir/core/SpatialPartitionBase.hpp
>      void scale_margin(const real_type scale, const system_type& sys,
The code snippet shown here is too confusing... I wanted to show the last line of this code fraction, the `scale_margin` function.

2021-01-29 17:40 UTC, yutakasi634 commented on mjolnir/core/SpatialPartitionBase.hpp
>      void scale_margin(const real_type scale, const system_type& sys,
Thank you, I could understand and fixed that!

2021-01-30 07:08 UTC, ToruNiina approved these changes

2021-01-30 07:15 UTC, merged