Fix read uniform global potential
Mjolnir-MD/Mjolnir pull request #321
Opened 2022-05-26 12:40 UTC by yutakasi634

## Problem
When using UniformLennardJonesPotential or UniformCubicPanPotential, if the parameters table is empty, the leading_participants function of EmptyCombinationRule returns the range in which the begin and end positions are the same. This makes segmentation fault errors in runtime.

## Change
In the no parameters case of these potentials, all particles in the system are considered participants. Based on this, I made the empty parameter case and also considered all particles as participants, and raise warnings similar to the previous version of Mjolnir.

I don't know the correct behavior of the empty parameters table case, so if this is not appropriate, I'm sorry about that.

2022-05-26 13:14 UTC, ToruNiina requested changes
Okay, thank you. I confirmed that there is a bug you pointed out.
I think the fix is okay. But for the safety, we can add an assertion that checks if the `participants` is not empty.

I found that, not only `EmptyCombinationRule`, but also `CombinationTable` and `LorentzBertherotRule` also has similar potential bug. Do you have a spare time to add the assertion to the constructor of those 3 classes? If not, I will do that later.

2022-05-26 13:14 UTC, ToruNiina commented on mjolnir/input/read_global_potential.hpp
> +                             "simply remove the part from the input file.");
```suggestion
                             "simply remove or comment the part out from the input file.");
```
I now think it is better to mention about comment.

2022-05-26 13:14 UTC, ToruNiina commented on mjolnir/input/read_global_potential.hpp
> +                             "simply remove the part from the input file.");
```suggestion
                             "simply remove or comment the part out from the input file.");
```
same as the above.

2022-05-26 13:44 UTC, ToruNiina reviewed
typo

2022-05-26 13:44 UTC, ToruNiina commented on mjolnir/forcefield/global/ParameterList.hpp
> +        assert(partisipants.size() != 0);
```suggestion
        assert(participants.size() != 0);
```

2022-05-26 14:33 UTC, ToruNiina approved these changes

2022-05-26 14:42 UTC, yutakasi634 commented
I added the assertions and typo. You seem already confirm and approved that. Thank you!

2022-05-26 15:14 UTC, ToruNiina commented
I found several tests are failing because of the assertion.

Those check if a specified interactions are read but does not check the value of parameters. Parameter values are checked in other test codes.
Since those test does not focus on the parameters set in a global potential, I just left the `parameters` empty in a test input. We can add a placeholder value to the test input.

2022-05-27 02:25 UTC, yutakasi634 commented
OK. I added content to those parameters and those tests were fixed. Please check it.

2022-05-27 13:49 UTC, ToruNiina approved these changes

2022-05-27 13:49 UTC, merged

2022-05-27 13:49 UTC, ToruNiina commented
thank you!